updated .env logic + mitigate migrate errors

diff --git a/.github/workflows/deploy_stage.yaml b/.github/workflows/deploy_stage.yaml
--- a/.github/workflows/deploy_stage.yaml
+++ b/.github/workflows/deploy_stage.yaml
@@ -40,20 +40,20 @@ jobs:
 
       - name: Create backend .env file
         run: |
-          cp deployments/.env.backend.stage backend/.env
-          echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> backend/.env
-          echo "DJANGO_DATABSE_PASSWORD=${{ secrets.DJANGO_DATABSE_PASSWORD }}" >> backend/.env
-          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> backend/.env
-          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> backend/.env
-          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> backend/.env
-          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> backend/.env
-          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> backend/.env
-          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> backend/.env
-          echo "DJANGO_GOOGLE_OAUTH2_CLIENT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_ID }}" >> backend/.env
-          echo "DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET }}" >> backend/.env
-          echo "DJANGO_GOOGLE_OAUTH2_PROJECT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_PROJECT_ID }}" >> backend/.env
-          echo "DJANGO_EMAIL_HOST_USER=${{ secrets.DJANGO_EMAIL_HOST_USER }}" >> backend/.env
-          echo "DJANGO_EMAIL_HOST_PASSWORD=${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}" >> backend/.env
+          cp deployments/.env.backend.stage backend/.env.temp
+          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> backend/.env.temp
+          echo "DJANGO_DATABSE_PASSWORD=${{ secrets.DJANGO_DATABSE_PASSWORD }}" >> backend/.env.temp
+          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> backend/.env.temp
+          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> backend/.env.temp
+          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> backend/.env.temp
+          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> backend/.env.temp
+          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> backend/.env.temp
+          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> backend/.env.temp
+          echo "DJANGO_GOOGLE_OAUTH2_CLIENT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_ID }}" >> backend/.env.temp
+          echo "DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET }}" >> backend/.env.temp
+          echo "DJANGO_GOOGLE_OAUTH2_PROJECT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_PROJECT_ID }}" >> backend/.env.temp
+          echo "DJANGO_EMAIL_HOST_USER=${{ secrets.DJANGO_EMAIL_HOST_USER }}" >> backend/.env.temp
+          echo "DJANGO_EMAIL_HOST_PASSWORD=${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}" >> backend/.env.temp
 
         continue-on-error: false
 
@@ -61,9 +61,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: backend-dir
-          path: |
-            backend
-            backend/.env
+          path: backend
         continue-on-error: false
 
   deploy:
@@ -131,7 +129,7 @@ jobs:
           host: ${{ secrets.VPS_HOST_STAGE }}
           username: ${{ secrets.VPS_USERNAME }}
           key: ${{ secrets.VPS_SSH_KEY }}
-          source: "backend/*,backend/.env"
+          source: "backend/*"
           target: "/home/azureuser/backend-dev.vezmir.ai.new"
           strip_components: 1
         continue-on-error: false
@@ -145,8 +143,13 @@ jobs:
           script: |
             source /home/azureuser/.stage-vezmir/bin/activate
             cd /home/azureuser/backend-dev.vezmir.ai.new
+            mv backend/.env.temp backend/.env
             pip install -r requirements.txt
             python manage.py migrate
+            if [ $? -ne 0 ]; then
+              echo "Migration failed"
+              exit 1
+            fi
             deactivate
         continue-on-error: false
 
